[profile.default]
src = 'src'
out = 'out'
optimizer = true
optimizer_runs = 200
libs = ['lib']
optimizer = true
optimizer_runs = 300

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
number_underscore = "thousands"
quote_style = "double"
tab_width = 4

[profile.hf]
fuzz = { runs = 2_000, max_test_rejects = 1_000_000_000}

[profile.ci]
fuzz = { runs = 200, max_test_rejects = 100_000_000}

# See more config options https://github.com/foundry-rs/foundry/tree/master/config